### ISSUE TITLE
Think thread support might be broken

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/newton.mod#2]
Hi Brucey,

Finally got around to updating, but I now get this runtime error dialog on trying anything on Win32 x86/x64 (nothing appears in the program console output):

---
## OK   

Clicking OK then pops up:

---
## OK   

OK'ing this then ends the program, no error messages.

This happens with my examples and with your example_01 at least. Presumably related to the last update re. GC/threads!

Seems to be a gcc thing:

https://encrypted.google.com/search?hl=en&q=%22threads%20explicit%20registering%22

**Comment by woollybah** [comment]
Seems I hadn't pushed a brl.blitz GC initialisation change.
Let me know if that fixes it.

**Comment by DruggedBunny** [comment]
That did it Brucey, thanks!

I tried a celebratory build of my Newton test on all (Win32) combinations, something I've never tried before -- all mixes of 32/64/threaded/non-threaded/debug/release -- and all worked, apart from the multithreaded debug builds (x86 and x64), which give "EXCEPTION_ACCESS_VIOLATION" on launch, both in my test and your example_01 in newton.mod.

A simple _Print "Hello"_ works fine, but not going beyond that tonight!

I lied... just added a bunch of Prints to newton.mod's example_01.bmx, and it crashes on world.Update(1.0/60.0) -- line 24.

**Comment by woollybah** [comment]
I just tried mt builds on Win32, x86 and x64, of the two examples, and they run okay for me.
Make sure you've done a full rebuild for mt of everything - something I've found when working on bmk is that often during my build/test cycle all is well until I do the final mt build, then it just crashes on startup.... which is explained by my mt builds are only compiled periodically, so some files may be out-of-date (in relation to stuff that bcc is generating). The fix is always to rebuild mt modules, and everything works again.

**Comment by woollybah** [comment]
It appears to be an issue with Newton's thread callback into BlitzMax in threaded-debug mode. Happens on OS X too - which is useful as you get proper backtraces : 

```
0   example_01.debug.mt             0x000000010b0e7625 bbThreadGetData + 21
1   example_01.debug.mt             0x000000010b0db8ef brl_appstub_debugger_mt_stdio_GetDbgState + 111 
2   example_01.debug.mt             0x000000010b0ddd57 brl_appstub_debugger_mt_stdio_OnDebugEnterScope + 23 
3   example_01.debug.mt             0x000000010affa6d7 newton_dynamics_TNBody__defaultForceAndTorqueCallback_v_pbfi + 279 
```

Based on this, I'm presuming that BlitzMax isn't expecting to be in a thread created by something else, and therefore data that it feels should be available for the debugger, doesn't exist...

**Comment by woollybah** [comment]
Okay... I think I've got it working on OS X (pthread)...  the thread needs to "register" itself with BlitzMax (much in the same way as we are registering it with the GC). Once that's done, it doesn't crash any more.
It's all a bit low-level down there though, so there may be some further work required.
I'll have a look at Win32 next... ;-)

**Comment by DruggedBunny** [comment]
Nice sleuthing! It doesn't bother me, for what it's worth, as I rarely use anything other than Print-based debugging, but I imagine it'll probably bother you and so HAVE to be fixed... :P

**Comment by woollybah** [comment]
I've pushed changes to both brl and newton modules.
Please let me know how you get on with that. It's working for me here testing the two examples in threaded debug on OS X and Win32.

**Comment by woollybah** [comment]
Technical notes : Newton now registers the thread with BlitzMax (as well as the GC). This results in the creation of thread-specific data that BlitzMax uses in debug mode to keep track of its debug/call stack, etc.

**Comment by DruggedBunny** [comment]
Hi Brucey, it's still not quite there -- it failed to build first time (forgot to note error, was gc/threaded related!) but I suspected I needed a new brl.mod; just updated, and now it fails while building example01 under both x86 and x64 Debug/Threaded:

`Building example_01
[ 84%] Processing:**debugger_mt.stdio.bmx**
Compile Error: Syntax error - expecting ')'.
[X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/debugger_mt.stdio.bmx;341;0]
Build Error: failed to compile X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/debugger_mt.stdio.bmx
Process complete`

This error falls inside a ?Win32 section of debugger_mt.stdio.bmx, line 341:

`
        Return String.FromWParam( (WParam Ptr p)[0] )
`
There's a similar line just after that:
`
        Return String.FromLParam( (LParam Ptr p)[0] )
`
I can't even tell if that _should_ build! I guess so, and the brackets seem to match!

Just checked, and **non-threaded** debug (x86 and x64) also gives this error, so seems to be Debug-specific now, not requiring threading enabled to fall over.

Dunno if relevant: tried to build the module on its own to see if it gave the same result (normal "Build" from IDE) and it says:
`
Building debugger_mt.stdio
REMAINING :
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/.bmx/appstub.bmx.debug.mt.win32.x86.c
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/.bmx/appstub.bmx.debug.mt.win32.x86.o
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.gui.debug.mt.win32.x86.c
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.gui.debug.mt.win32.x86.o
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/appstub.bmx
  X:/BlitzMaxNG_077/mod/brl.mod/appstub.mod/debugger_mt.stdio.bmx
**circular dependency!**
Process complete

`

**Comment by DruggedBunny** [comment]
Addition: it does this for a simple **Print "Hello"**, BTW, nothing to do with Newton.

**Comment by DruggedBunny** [comment]
Apologies for stream of comments -- this just showed up while trying a non-debug, non-threaded build of my example!

`[ 90%] Processing:system.win32.bmx
Compile Error: **Type 'wparam' not found**
[X:/BlitzMaxNG_077/mod/brl.mod/systemdefault.mod/system.win32.bmx;27;0]
Build Error: failed to compile X:/BlitzMaxNG_077/mod/brl.mod/systemdefault.mod/system.win32.bmx
Process complete
`

Yep, same for **Print "Hello"**...

IDE highlights this in the above file:

`
Function bbSystemEmitOSEvent( hwnd:Byte Ptr,msg,wparam:WParam,lparam:LParam,source:Object )
`
(The previous error was failing on a wparam-related line.)

**Comment by woollybah** [comment]
You will need the latest bcc to build against the latest brl/pub modules.

**Comment by woollybah** [comment]
From a completely clean build - everything straight out of git - the examples run as expected (in mt-debug).

**Comment by DruggedBunny** [comment]
I'm having no joy at the moment -- having to completely rebuild my NG setup as updating via Git hasn't worked.

Using all-new (straight download) versions of everything (in brand-new install folder) I'm getting Exception Access Violation on any use of non-Debug Print! Built all commands in Debug vanilla to get them working, but final non-Debug executables still fail... fun, fun, fun! Will give Frisky a go...

**Comment by DruggedBunny** [comment]
Further to my other "issue" reports -- I can finally confirm that this particular problem appears to be resolved (subject to the apparent [Vulkan init thing](https://github.com/bmx-ng/pub.mod/issues/13) being commented out).

Frisky-built NG is now building my newton/openb3d stuff in all target/architecture/build combinations tested so far -- done x86 debug/non-debug in threaded/non-threaded, plus just built x64 debug + threaded -- not got through the rest yet, but assume fixed from the evidence thus far!

Will close this one as the non-Debug Print exception (which isn't actually Print-specific after all) is apparently weirdly related to the Vulkan initialisation, but having worked around that, this particular problem appears to be resolved.

Thanks again!
